In [1]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
import json

In [13]:
sns.set()

/Users/Dino/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

In [4]:
with open('newjson.json', 'r') as f:
    rjd = json.load(f)

In [5]:
ajd = rjd['RECORDS']

In [7]:
djd = pd.read_json(json.dumps(ajd), orient='records')

In [9]:
df = djd

In [10]:
df

,dopasPerTab,gini,idx,inkCntList,maxInksPerTab,oID,qtyPerTab,runTime,stationTypeId,tabID,tab_score_reg,tab_score_weighted,totInksPerTab,tot_imps_per_tab
0,2,0.000000,0,"[2, 2]",2,257399,20,1,2,68646,2.82843,339.41100,4,120
1,2,0.300000,1,"[4, 1]",4,261506,93,6443,1,73435,3.16228,1470.46000,5,465
2,2,0.100000,2,"[2, 3]",3,262287,37,3787,2,74340,3.16228,819.03000,5,259
3,2,0.000000,3,"[2, 2]",2,262427,100,21659,1,74498,2.82843,565.68500,4,200
4,2,0.300000,4,"[1, 4]",4,262456,50,2567,1,74529,3.16228,790.56900,5,250
5,1,0.000000,5,[1],1,262604,50,2173,2,74708,1.00000,100.00000,1,100
6,2,0.000000,6,"[1, 1]",1,262641,100,4735,1,74755,2.00000,800.00000,2,400
7,1,0.000000,7,[1],1,262669,6,398,2,74787,1.41421,16.97060,1,12
8,2,0.166667,8,"[2, 1]",2,262730,100,8956,1,74858,2.44949,489.89800,3,200
9,1,0.000000,9,[2],2,262865,59,4567,1,75013,1.41421,166.87700,2,118
10,1,0.000000,10,[2],2,262955,45,3795,2,75116,1.41421,254.55800,2,180
11,2,0.000000,11,"[1, 1]",1,262973,50,3684,2,75135,2.00000,200.00000,2,100
12,2,0.000000,12,"[4, 4]",4,262983,105,13907,1,75147,4.00000,2520.00000,8,630
13,2,0.000000,13,"[1, 1]",1,263000,10,1504,2,75168,2.00000,80.00000,2,40
14,2,0.166667,14,"[2, 1]",2,263004,24,5481,2,75173,2.44949,352.72700,3,144
15,1,0.000000,15,[2],2,263052,7,477,2,75225,2.00000,28.00000,2,14
16,2,0.000000,16,"[1, 1]",1,263053,7,2141,2,75226,2.00000,56.00000,2,28
17,1,0.000000,17,[1],1,263060,6,1382,2,75234,1.00000,12.00000,1,12
18,1,0.000000,18,[2],2,263072,36,4611,2,75246,1.41421,203.64700,2,144
19,1,0.000000,19,[2],2,263083,12,1204,2,75259,1.41421,67.88220,2,48
20,1,0.000000,20,[1],1,263096,7,454,2,75274,1.00000,14.00000,1,14
21,2,0.000000,21,"[2, 2]",2,263097,25,3683,2,75275,2.82843,353.55300,4,125
22,1,0.000000,22,[1],1,263104,3,754,2,75283,1.00000,6.00000,1,6
23,2,0.166667,23,"[2, 1]",2,263107,53,6376,2,75286,2.44949,389.46900,3,159
24,2,0.000000,24,"[1, 1]",1,263109,10,1287,2,75288,2.00000,40.00000,2,20
25,2,0.166667,25,"[4, 2]",4,263111,35,13547,2,75290,3.46410,1333.68000,6,385
26,2,0.000000,26,"[1, 1]",1,263112,12,1692,2,75291,2.00000,96.00000,2,48
27,2,0.166667,27,"[4, 2]",4,263113,22,6919,2,75292,3.46410,914.52300,6,264
28,1,0.000000,28,[5],5,263117,10,1364,2,75297,2.23607,111.80300,5,50
29,1,0.000000,29,[1],1,263128,3,1308,2,75311,1.00000,6.00000,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6688,2,0.000000,6688,"[1, 1]",1,306970,18,1280,2,125307,2.00000,72.00000,2,36
6689,1,0.000000,6689,[1],1,306984,8,293,2,125321,1.00000,8.00000,1,8
6690,2,0.000000,6690,"[1, 1]",1,306995,25,2364,2,125333,2.00000,100.00000,2,50
6691,1,0.000000,6691,[1],1,306999,40,3850,2,125337,1.00000,120.00000,1,120
6692,2,0.000000,6692,"[2, 2]",2,307004,19,3,2,125342,2.82843,322.44100,4,114
6693,2,0.000000,6693,"[1, 1]",1,307011,4,1248,2,125350,2.00000,32.00000,2,16
6694,2,0.000000,6694,"[1, 1]",1,307030,30,5297,2,125367,2.00000,240.00000,2,120
6695,1,0.000000,6695,[1],1,307031,5,2057,2,125368,1.00000,10.00000,1,10
6696,2,0.166667,6696,"[2, 1]",2,307034,43,3611,2,125371,2.44949,315.98400,3,129
6697,1,0.000000,6697,[2],2,307046,30,3865,2,125383,1.41421,127.27900,2,90
6698,1,0.000000,6698,[1],1,307054,7,1872,2,125391,1.00000,14.00000,1,14
6699,1,0.000000,6699,[1],1,307074,20,1217,2,125415,1.00000,40.00000,1,40
6700,1,0.000000,6700,[1],1,307076,4,117,2,125421,1.00000,4.00000,1,4
6701,1,0.000000,6701,[1],1,307085,7,200,2,125432,1.00000,7.00000,1,7
6702,1,0.000000,6702,[2],2,307088,29,1633,2,125435,1.41421,123.03700,2,87
6703,1,0.000000,6703,[1],1,307092,3,735,2,125439,1.41421,8.48528,1,6
6704,2,0.166667,6704,"[2, 1]",2,307095,13,1766,2,125442,2.44949,95.53010,3,39
6705,2,0.000000,6705,"[2, 2]",2,307121,250,92725,1,125469,2.82843,1414.21000,4,500
6706,1,0.000000,6706,[1],1,307138,2,559,2,125486,1.00000,4.00000,1,4
6707,2,0.000000,6707,"[1, 1]",1,307163,28,27,2,125517,2.00000,112.00000,2,56
6708,1,0.000000,6708,[1],1,307164,30,1666,2,125518,1.00000,30.00000,1,30
6709,1,0.000000,6709,[1],1,307166,5,947,2,125521,1.00000,5.00000,1,5
6710,2,0.000000,6710,"[1, 1]",1,307167,7,1095,2,125522,2.00000,28.00000,2,14
6711,2,0.000000,6711,"[1, 1]",1,307187,11,1115,2,125543,2.44949,107.77800,2,44
6712,1,0.000000,6712,[2],2,307190,50,2765,2,125546,1.41421,141.42100,2,100
6713,1,0.000000,6713,[1],1,307195,11,1939,2,125551,1.00000,22.00000,1,22
6714,2,0.000000,6714,"[1, 1]",1,307200,10,1448,2,125560,2.00000,80.00000,2,40
6715,1,0.000000,6715,[1],1,307207,7,1276,2,125567,1.00000,7.00000,1,7
6716,1,0.000000,6716,[2],2,307277,15,2163,2,125662,1.41421,63.63960,2,45
6717,2,0.166667,6717,"[1, 2]",2,307335,43,3063,2,125731,2.44949,631.96800,3,258